Vagrant.configure("2") do |config|
    # Base box
    config.vm.box = "ubuntu/jammy64"

    # Hostname
    config.vm.hostname = "ubuntu"
    
    # Private network with static IP
    config.vm.network "private_network", ip: "192.168.0.10", hostname: true

    # Provider settings (Name, RAM, CPU, etc.)
    config.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu-22.04-jammy"
        vb.memory = 2048         # Set RAM size (MB)
        vb.cpus = 2              # Set number of CPU cores
    end

    # Default disk size (min 40GB for ubuntu/jammy64)
    config.vm.disk :disk, size: "40GB", primary: true

end